### ISSUE TITLE
Untyped Config Coercion Improvement

### ISSUE THREAD

**Issue by airstandley** [gtmanfred/figenv#9]
Random musing for a potential improvement.

Currently when no type annotation is present for a config and the found value is a string (regardless of if the source if the env, a callable, or a default), MetaConfig will attempt to guess the type based on the string's format.

One potential improvement might be to instead inspect the default or callable signature to try and determine typing information. None would be ignored and trigger fallback to guessing type based on string's format.

Examples:

APP_STRING = "1.2"  # default is a str type so assume value should be coerced to a string.
APP_INT = 1  # default is an int type so assume value should be coerced to an int.
APP_FLOAT = None # default is None so fallback to guessing based on the value string's format.

def APP_KEYS(cls) -> List[str]:  # default callable is type annotated to return  list[str] so assume value should be coerced to a list.
    return ["one", "two"]

def APP_ICONS(cls):  # Callable with no type annotations. Would either fallback as with None, or use return value as default to extract type from.
    return ["fileA.jpg", "fileB.svg"]

**Comment by gtmanfred** [comment]
I forgot about this issue, and had a problem where someone was having their function which returned a string of numbers, get converted to integers, so v1.3.0 includes this patch https://github.com/gtmanfred/figenv/commit/c82248b6b0ecd6adb816fdd6651e1a18bd8039d4

Which respects the annotation of the callable. Does this work for you? or should we have more of a discussion around better ways to accommodate this?

**Comment by gtmanfred** [comment]
Nevermind, i do see the problem, i just added this so that if you override a function with an environment variable, it still applies the annotation.

released in v1.4.0
